server:
  port: 8080
    error:
      include-binding-errors: always
      include-message: always

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    password: boot
    url: jdbc:postgresql://localhost:5432/dcbapp
    username: spring
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
