server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: boot
    url: jdbc:postgresql://localhost:5432/dcbapp
    username: spring
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to kwawingu
